controller:
  # Enabling Promethues metrics only for now
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  # Allow snippet anotations
  allowSnippetAnnotations: true

  # Set specific LoadBalancer IP address for Ingress service
  service:
    annotations:
      io.cilium/lb-ipam-ips: 10.0.0.110
