controller:
  image:
    # Using an older version that works on ARM
    repository: k8s.gcr.io/ingress-nginx/controller
    tag: "v1.0.4"
    digest: ""
  
  # Enabling Promethues metrics only for now
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  # Allow snippet anotations
  allowSnippetAnnotations: true

  # Use NodePort instead of LoadBalancer since we don't have Cilium IPAM
  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443
