apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom-hosts
  namespace: kube-system
data:
  CustomHosts: |
    10.0.0.12 example.homelab.yekvitka.com
    10.0.0.12 test.homelab.yekvitka.com
