apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # External-DNS annotations
    external-dns.alpha.kubernetes.io/hostname: "example.homelab.yekvitka.com"
    external-dns.alpha.kubernetes.io/target: "10.0.0.12"  # Use node IP
spec:
  rules:
  - host: example.homelab.yekvitka.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubernetes
            port:
              number: 443
