apiVersion: v1
kind: Secret
metadata:
  name: external-dns-rfc2136-credentials
  namespace: external-dns
stringData:
  rfc2136_tsig_secret: "J8kvIwtkvYXLUcVj6mROEBLHy6h3Gle3j91vS8aJB9c="
type: Opaque
