---
# Pi Cluster variables

#######################
# External Services   #
#######################

# Domain name
dns_domain: "picluster.local"

# External services hostnames
minio_hostname: "s3.picluster.local"
vault_hostname: "vault.picluster.local"
enable_letsencrypt: false
custom_ca: true
vault_dns: "{{ vault_hostname }}"

# Node1 IP for resolving hostnames locally
node1_ip: 10.0.0.11

#######
# K3S #
#######

# k3s version
k3s_version: v1.31.4+k3s1

# k3s master node VIP (loadbalancer)
k3s_api_vip: 10.0.0.11

# k3s shared token
k3s_token: "{{ vault.cluster.k3s.token }}"

# k3s config directory
k3s_config_directory: /etc/rancher/k3s
k3s_config_file: "{{ k3s_config_directory }}/config.yaml"
k3s_token_file: "{{ k3s_config_directory }}/token"
k3s_registries_file: "{{ k3s_config_directory }}/registries.yaml"

#######################
# MinIO Configuration #
#######################

# Minio S3 Server
minio_endpoint: "{{ minio_hostname }}:9091"
minio_url: "https://{{ minio_hostname }}:9091"

# Minio data dirs
minio_server_make_datadirs: true
minio_server_datadirs:
  - /storage/minio

# Minio admin credentials
minio_root_user: "minioadmin"
minio_root_password: "{{ vault.minio.root.password }}"

# Minio site region configuration
minio_site_region: "eu-west-1"

# Enabling TLS
minio_enable_tls: true
minio_validate_certificate: false

# Create Prometheus bearer token
minio_prometheus_bearer_token: true

# Minio Buckets and Users
minio_buckets:
  - name: restic
    versioning: false
    policy: private
  - name: longhorn
    versioning: true
    policy: private
  - name: velero
    versioning: false
    policy: private
  - name: loki
    versioning: false
    policy: private
  - name: tempo
    versioning: false
    policy: private
  - name: barman
    versioning: false
    policy: private

minio_users:
  - name: "{{ vault.minio.restic.user }}"
    password: "{{ vault.minio.restic.key }}"
    buckets_acl:
      - name: restic
        policy: read-write
  - name: "{{ vault.minio.longhorn.user }}"
    password: "{{ vault.minio.longhorn.key }}"
    buckets_acl:
      - name: longhorn
        policy: read-write
  - name: "{{ vault.minio.velero.user }}"
    password: "{{ vault.minio.velero.key }}"
    buckets_acl:
      - name: velero
        policy: read-write
  - name: "{{ vault.minio.loki.user }}"
    password: "{{ vault.minio.loki.key }}"
    buckets_acl:
      - name: loki
        policy: read-write
  - name: "{{ vault.minio.tempo.user }}"
    password: "{{ vault.minio.tempo.key }}"
    buckets_acl:
      - name: tempo
        policy: read-write
  - name: "{{ vault.minio.barman.user }}"
    password: "{{ vault.minio.barman.key }}"
    buckets_acl:
      - name: barman
        policy: read-write

#######################
# Vault configuration #
#######################

# renovate: datasource=github-releases depName=hashicorp/vault
vault_version: 1.18.3

vault_enable_tls: true
vault_init: true
vault_unseal: true
vault_unseal_service: true
vault_data_dir: /storage/vault
tls_skip_verify: "{{ not enable_letsencrypt }}"

# Configure KV
vault_kv_secrets:
  path: secret

#######################
# Ingress #
#######################

ingress_basic_auth_user: "{{ vault.ingress.admin.user }}"
ingress_basic_auth_passwd: "{{ vault.ingress.admin.password }}"
