---
# Encrypted variables - Ansible Vault
vault:
  # SAN
  san:
    iscsi:
      node_pass: s1cret0
      password_mutual: 0tr0s1cret0
  # K3s secrets
  cluster:
    k3s:
      token: s1cret0
  # traefik secrets
  traefik:
    basic_auth:
      user: admin
      passwd: s1cret0
  # Ingress secrets
  ingress:
    admin:
      user: admin
      password: s1cret0
  # Minio S3 secrets
  minio:
    root:
      user: minioadmin
      password: minioadmin
    admin:
      user: admin
      password: adminpassword
    restic:
      user: restic
      key: restic12345678
    longhorn:
      user: longhorn
      key: longhorn12345678
    velero:
      user: velero
      key: velero12345678
    loki:
      user: loki
      key: loki12345678
    tempo:
      user: tempo
      key: tempo12345678
    barman:
      user: barman
      key: barman12345678
  # Vault secrets
  vault:
    root:
      token: root_token
    unseal:
      key: unseal_key
      user: root
    restic:
      user: restic
      key: supers1cret0
    longhorn:
      user: longhorn
      key: supers1cret0
    velero:
      user: velero
      key: supers1cret0
    loki:
      user: loki
      key: supers1cret0
    tempo:
      user: tempo
      key: supers1cret0
  # elastic search
  elasticsearch:
    es-admin:
      user: admin
      password: s1cret0
    es-fluentd:
      user: fluentd
      password: s1cret0
    es-prometheus:
      user: prometheus
      password: s1cret0
  # Fluentd
  fluentd:
    shared_key:
      value: s1cret0
  # Grafana
  grafana:
    admin:
      user: admin
      password: s1cret0

