---
all:
  children:
    control:
      hosts:
        pimaster:
          hostname: pimaster
          ansible_host: localhost
          ansible_connection: local
    external:
      hosts:
        # Removing external s3 and vault hosts as they'll be hosted on node1
    picluster:
      hosts:
        node1:
          hostname: node1
          ansible_host: 10.0.0.11
          ip: 10.0.0.11
          mac: D8:3A:DD:3B:47:08
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        node2:
          hostname: node2
          ansible_host: 10.0.0.12
          ip: 10.0.0.12
          mac: D8:3A:DD:3B:46:ED
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          k3s_primary_control_node: true
        node3:
          hostname: node3
          ansible_host: 10.0.0.13
          ip: 10.0.0.13
          mac: D8:3A:DD:D4:99:82
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        node4:
          hostname: node4
          ansible_host: 10.0.0.14
          ip: 10.0.0.14
          mac: D8:3A:DD:D4:8E:FC
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        node5:
          hostname: node5
          ansible_host: 10.0.0.15
          ip: 10.0.0.15
          mac: D8:3A:DD:3B:47:2F
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
    raspberrypi:
      hosts:
        node[1:6]:
    k3s_cluster:
      children:
        k3s_master:
          hosts:
            node[2:3]:
        k3s_worker:
          hosts:
            node[4:5]:
    dns:
      hosts:
        node1:
    pxe:
      hosts:
        node1:
    vault:
      hosts:
        node1:
    s3:
      hosts:
        node1:
    haproxy:
      hosts:
        node1:
    san:
      hosts:
        node1: