---

- name: Install load balancer
  hosts: haproxy
  gather_facts: true
  tags: [install]
  become: true
  roles:
    - role: haproxy

- name: Install K3S prerequisites
  hosts: k3s_cluster
  gather_facts: true
  tags: [install]
  become: true
  pre_tasks:
    - name: Include vault variables
      include_vars: "vars/vault.yml"
      tags: ["always"]
    - name: Include picluster variables
      include_vars: "vars/picluster.yml"
      tags: ["always"]
  roles:
    - role: k3s/prereq

- name: Install K3S master node
  hosts: k3s_master
  tags: [install]
  become: true
  pre_tasks:
    - name: Include vault variables
      include_vars: "vars/vault.yml"
      tags: ["always"]
    - name: Include picluster variables
      include_vars: "vars/picluster.yml"
      tags: ["always"]
  roles:
    - role: k3s/master
    - role: ricsanfre.k8s_cli

- name: Install K3S worker nodes
  hosts: k3s_worker
  tags: [install]
  become: true
  pre_tasks:
    - name: Include vault variables
      include_vars: "vars/vault.yml"
      tags: ["always"]
    - name: Include picluster variables
      include_vars: "vars/picluster.yml"
      tags: ["always"]
  roles:
    - role: k3s/worker

- name: Label K3S worker nodes
  hosts: k3s_master
  tags: [config]
  pre_tasks:
    - name: Include vault variables
      include_vars: "vars/vault.yml"
      tags: ["always"]
    - name: Include picluster variables
      include_vars: "vars/picluster.yml"
      tags: ["always"]
  tasks:
    - name: "Wait for worker nodes to be ready"
      command:
        cmd: "kubectl get nodes {{ item }}"
      register: nodes
      until:
        - '" Ready "  in nodes.stdout'
      retries: 30
      delay: 10
      with_items: "{{ groups['k3s_worker'] }}"
      
    - name: label k3s worker nodes
      command:
        cmd: "kubectl label nodes {{ item }} kubernetes.io/role=worker"
      with_items: "{{ groups['k3s_worker'] }}"
      ignore_errors: true

- name: Get Kubernets config file
  hosts: k3s_master
  tags: [kube-config]
  tasks:
    - name: Get k3s config file
      run_once: true
      ansible.builtin.slurp:
        src: /etc/rancher/k3s/k3s.yaml
      register: kubeconfig_base64

    - name: Write Kubernetes config file with the correct cluster address
      ansible.builtin.copy:
        content: "{{ kubeconfig_base64.content | b64decode | replace('127.0.0.1', k3s_api_vip ) }}"
        dest: "~/.kube/config"
        mode: 0600
      delegate_to: localhost
      run_once: true

- name: Verify cluster is ready
  hosts: k3s_master[0]
  tags: [verify]
  tasks:
    - name: Get node status
      command: "kubectl get nodes -o wide"
      register: node_status
      
    - name: Display node status
      debug:
        msg: "{{ node_status.stdout_lines }}"
        
    - name: Check that all nodes are Ready
      shell: "kubectl get nodes | grep -v NotReady | grep -c Ready || echo 0"
      register: ready_nodes
      failed_when: ready_nodes.stdout | int < groups['k3s_cluster'] | length
      
    - name: Cluster status message
      debug:
        msg: "Kubernetes cluster is fully operational with {{ ready_nodes.stdout }} Ready nodes"