---
- hosts: picluster
  become: true
  gather_facts: false
  tasks:
    - name: Shutdown
      command: shutdown now
      ignore_errors: true

- hosts: gateway
  become: true
  gather_facts: false
  tasks:
    - name: Shutdown
      command: shutdown now
      ignore_errors: true
