# Cilium operator config
operator:
  replicas: 2  # Match the number of master nodes
  # Roll out cilium-operator pods automatically when configmap is updated.
  rollOutPods: true

  # Install operator on control plane nodes
  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"

# Roll out cilium agent pods automatically when ConfigMap is updated.
rollOutCiliumPods: true

# K8s API service
k8sServiceHost: 10.0.0.11
k8sServicePort: 6443

# Replace Kube-proxy
kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256

# -- Configure IP Address Management mode.
ipam:
  operator:
    clusterPoolIPv4PodCIDRList: "10.42.0.0/16"

# Configure L2 announcements
l2announcements:
  enabled: true
externalIPs:
  enabled: true

# Increase the k8s api client rate limit
k8sClientRateLimit:
  qps: 50
  burst: 200
