services:
  ansible-runner:
    image: ansible-runner
    build:
      context: .
    command: tail -f /dev/null
    container_name: ansible-runner
    restart: unless-stopped
    user: runner
    volumes:
      - ./../ansible:/ansible:ro
      - ./../kubernetes:/kubernetes
      - ./../metal/x86/pxe-files:/metal/x86/pxe-files
      - ./runner/.gnupg:/home/runner/.gnupg
      - ./../ansible/.vault:/home/runner/.vault  # Changed this line
      - ./runner/.secrets:/home/runner/.secrets
      - ./runner/scripts:/home/runner/scripts
      - ./runner/.ssh:/home/runner/.ssh
      - ./runner/.kube:/home/runner/.kube
      - ./certbot/log:/var/log/letsencrypt
      - ./certbot/config:/etc/letsencrypt
      - ./certbot/work:/var/lib/letsencrypt
    environment:
      - ANSIBLE_CONFIG=home/picluster/ansible/ansible.cfg
      - ANSIBLE_VAULT_PASSWORD_FILE=/home/picluster/ansible/.vault/vault_pass.sh
    working_dir: home/picluster/ansible
