apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-zones
  namespace: kube-system
data:
  yekvitka.local.db: |
    $ORIGIN yekvitka.local.
    @	3600 IN	SOA ns.yekvitka.local. hostmaster.yekvitka.local. (
            2025091101 ; serial
            7200       ; refresh (2 hours)
            3600       ; retry (1 hour)
            1209600    ; expire (2 weeks)
            3600       ; minimum (1 hour)
            )

            3600 IN NS ns.yekvitka.local.
            3600 IN A  10.0.0.1

    ns      3600 IN A  10.0.0.1
  
  # TSIG key configuration
  externaldns-key.key: |
    key "externaldns-key" {
      algorithm hmac-sha256;
      secret "J8kvIwtkvYXLUcVj6mROEBLHy6h3Gle3j91vS8aJB9c=";
    };
