apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  yekvitka.local: |
    yekvitka.local:53 {
      errors
      cache 30
      hosts {
        10.0.0.11 s3.yekvitka.local vault.yekvitka.local
        10.0.0.13 rancher.yekvitka.local grafana.yekvitka.local loki.yekvitka.local tempo.yekvitka.local
        fallthrough
      }
    }
