apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts {
          10.0.0.13 rancher.yekvitka.local grafana.yekvitka.local loki.yekvitka.local tempo.yekvitka.local
          10.0.0.11 s3.yekvitka.local vault.yekvitka.local
          fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
    yekvitka.local:53 {
        errors
        cache 30
        hosts {
          10.0.0.13 rancher.yekvitka.local grafana.yekvitka.local loki.yekvitka.local tempo.yekvitka.local
          10.0.0.11 s3.yekvitka.local vault.yekvitka.local
        }
    }
